databases:
  - name: dj_taskmanager
    plan: free
    databaseName: dj_taskmanager
    user: dj_taskmanager_user

services:
  - type: web
    plan: free
    name: dj_taskmanager
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn task_manager.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dj_taskmanager
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4